version: '3'
services: 
  react-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/react/node_modules
      - .:/app/react
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/react/node_modules
      - .:/app/react
    command: ["npm", "run", "test"]